[features]
seeds = false
skip-lint = false
[programs.localnet]
depositplus = "GeTM4QBoYJ6sStEohmNRiDiARJTK4jjNsjxsVp6A5jHc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/qn-milano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
